// SPDX-License-Identifier: GPL-2.0+

#include <asm/global_data.h>
#include <command.h>
#include <config.h>
#include <console.h>
#include <env.h>
#include <flash.h>
#include <generated/version_autogenerated.h>
#include <malloc.h>
#include <net.h>
#include <linux/delay.h>
#include <linux/errno.h>
#include <lwip/dhcp.h>
#include <lwip/err.h>
#include <lwip/netif.h>
#include <lwip/tcp.h>
#include <lwip/timeouts.h>

DECLARE_GLOBAL_DATA_PTR;

#define DHCP_TIMEOUT_MS    10000
#define HTTP_POLL_MS       10
#define FW_BUF_MAX        (8 * 1024 * 1024)
#define HTTP_PORT         80

static struct netif *httpd_netif;
static struct tcp_pcb *httpd_pcb;

static unsigned char *fw_buf;
static unsigned int fw_buf_len;
static unsigned int fw_content_len;

/* 根页面 */
static const char g_index_html[] =
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html; charset=utf-8\r\n"
"Connection: close\r\n"
"Server: 不死 U-Boot\r\n"
"\r\n"
"<!DOCTYPE html>"
"<html lang=\"zh\">"
"<head>"
"<meta charset=\"utf-8\">"
"<title>不死 U-Boot - Web 恢复模式</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:Arial,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:16px}"
".container{max-width:700px;margin:0 auto}"
"h1{text-align:center;color:#e94560;margin-bottom:16px;font-size:20px}"
".card{background:#16213e;border:1px solid #0f3460;border-radius:8px;padding:14px;margin-bottom:14px}"
".card h2{color:#e94560;font-size:15px;margin-bottom:8px;border-bottom:1px solid #0f3460;padding-bottom:5px}"
"table{width:100%;border-collapse:collapse}"
"td{padding:5px 0;border-bottom:1px solid #1a1a2e;font-size:13px}"
"td:first-child{color:#888;width:120px}"
"input[type=file]{width:100%;padding:8px;background:#1a1a2e;color:#e0e0e0;border:1px solid #0f3460;border-radius:4px;margin:6px 0}"
"input[type=submit]{background:#e94560;color:#fff;border:none;padding:8px 20px;border-radius:4px;cursor:pointer;font-size:13px}"
".btn{display:inline-block;background:#e94560;color:#fff;padding:7px 18px;border-radius:4px;text-decoration:none;font-size:13px;margin-right:6px}"
".footer{text-align:center;color:#555;font-size:11px;margin-top:16px}"
"</style>"
"</head>"
"<body>"
"<div class=\"container\">"
"<h1>不死 U-Boot - Web 恢复模式</h1>"
"<div class=\"card\">"
"<h2>系统信息</h2>"
"<table>"
"<tr><td>版本</td><td>%s</td></tr>"
"<tr><td>设备</td><td>QEMU ARM / RV1108</td></tr>"
"<tr><td>内存</td><td>%lu MB</td></tr>"
"<tr><td>IP 地址</td><td>%s</td></tr>"
"</table>"
"</div>"
"<div class=\"card\">"
"<h2>固件升级</h2>"
"<p style=\"font-size:12px;color:#888;margin-bottom:8px\">选择固件文件 (最大 8MB)，点击升级按钮。请勿断电!</p>"
"<form action=\"/upload\" method=\"post\" enctype=\"multipart/form-data\">"
"<input type=\"file\" name=\"firmware\" accept=\".bin,.img\" required>"
"<input type=\"submit\" value=\"开始升级\">"
"</form>"
"</div>"
"<div class=\"card\">"
"<h2>操作</h2>"
"<a class=\"btn\" href=\"/reboot\">重启设备</a>"
"</div>"
"<div class=\"footer\">不死 U-Boot Web Recovery &copy; 2024</div>"
"</div>"
"</body>"
"</html>";

static char g_upgrade_page[1024];

#define HTTP_404 "HTTP/1.1 404 Not Found\r\nContent-Type: text/html\r\nConnection: close\r\n\r\n<html><body><h1>404</h1></body></html>"
#define HTTP_BAD  "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n"

/* ========== 网络辅助 ========== */

static err_t http_send(struct tcp_pcb *pcb, const void *data, unsigned int len)
{
	err_t err;
	unsigned int to_send = len > tcp_sndbuf(pcb) ? tcp_sndbuf(pcb) : len;

	if (to_send == 0)
		return ERR_OK;

	err = tcp_write(pcb, data, to_send, TCP_WRITE_FLAG_COPY);
	if (err == ERR_OK) {
		tcp_output(pcb);
		return ERR_OK;
	}
	return err;
}

static void http_close(struct tcp_pcb *pcb)
{
	tcp_arg(pcb, NULL);
	tcp_recv(pcb, NULL);
	tcp_sent(pcb, NULL);
	tcp_err(pcb, NULL);
	tcp_close(pcb);
}

/* ========== Flash 写入 ========== */

static int write_to_flash(unsigned char *data, unsigned int len)
{
#if defined(CONFIG_SPI_FLASH)
	struct udevice *dev;
	struct mtd_info *mtd;
	int ret;
	ret = spi_flash_probe_bus_cs(CONFIG_SF_DEFAULT_BUS,
				     CONFIG_SF_DEFAULT_CS,
				     CONFIG_SF_DEFAULT_SPEED,
				     CONFIG_SF_DEFAULT_MODE, &dev);
	if (ret) {
		printf("httpd: SPI flash 探测失败: %d\n", ret);
		return -1;
	}
	mtd = dev_get_uclass_plat(dev);
	if (!mtd) {
		printf("httpd: 无法获取 MTD 设备\n");
		return -1;
	}
	ret = mtd->_erase(mtd, &(struct erase_info){ .addr = 0, .len = len });
	if (ret) {
		printf("httpd: 擦除失败: %d\n", ret);
		return -1;
	}
	return mtd->_write(mtd, 0, len, &len, data);
#elif defined(CONFIG_MTD_NOR_FLASH)
	flash_info_t *info = &flash_info[0];
	unsigned long sec;

	if (!info->size || !info->sector_count) {
		printf("httpd: CFI Flash 未探测, 保存到内存\n");
		goto mem_save;
	}

	sec = flash_sector_size(info, 0);
	if (!sec) {
		printf("httpd: Flash 扇区大小为0, 保存到内存\n");
		goto mem_save;
	}

	printf("httpd: 写入 CFI NOR Flash (%u 字节, 扇区%luB)...\n", len, sec);
	{
		unsigned long fw_addr = 4 * 1024 * 1024;
		unsigned long addr = fw_addr;
		unsigned int offset = 0;
		while (offset < len) {
			unsigned int s = addr / sec;
			if (s >= info->sector_count) break;
			flash_erase(info, s, s);
			addr += sec;
			offset += sec;
		}
	}
	{
		int r = flash_write((char *)data, 4 * 1024 * 1024, len);
		printf("httpd: flash_write 返回 %d\n", r);
		return (r == 0) ? 0 : -1;
	}
#else
	printf("httpd: 无 Flash 驱动\n");
#endif

mem_save:
	printf("httpd: 固件已缓存于内存 (%u 字节)\n", len);
	return 0;
}

/* ========== HTTP 回调 ========== */

struct http_conn {
	enum { HTTP_RECV_REQ, HTTP_RECV_UPLOAD } state;
	char *req_buf;
	unsigned int req_len;
};

static err_t http_recv_cb(void *arg, struct tcp_pcb *pcb, struct pbuf *p,
			  err_t err)
{
	struct http_conn *conn;
	char *req;
	unsigned int len;

	if (!p) {
		http_close(pcb);
		free(arg);
		return ERR_OK;
	}

	conn = arg;
	if (!conn) {
		pbuf_free(p);
		return ERR_OK;
	}

	if (conn->state == HTTP_RECV_UPLOAD) {
		unsigned int total = 0;
		struct pbuf *q;

		for (q = p; q; q = q->next)
			total += q->len;

		if (!fw_buf || fw_buf_len + total > FW_BUF_MAX) {
			pbuf_free(p);
			http_close(pcb);
			free(conn);
			return ERR_MEM;
		}

		for (q = p; q; q = q->next) {
			memcpy(fw_buf + fw_buf_len, q->payload, q->len);
			fw_buf_len += q->len;
		}
		pbuf_free(p);

		if (fw_buf_len >= fw_content_len) {
			/* 去掉 multipart 尾部 */
			int trim = 0;
			while (trim < 128 && trim < (int)fw_buf_len &&
			       fw_buf[fw_buf_len - 1 - trim] != '\n') trim++;
			trim += (trim < (int)fw_buf_len && trim < 64) ? 1 : 0;
			while (trim < 128 && trim < (int)fw_buf_len &&
			       fw_buf[fw_buf_len - 1 - trim] != '\n') trim++;
			trim += (trim < (int)fw_buf_len && trim < 64) ? 1 : 0;
			fw_buf_len -= (trim < (int)fw_buf_len) ? trim : 0;

			printf("httpd: 固件接收完成, %u 字节\n", fw_buf_len);
			int r = write_to_flash(fw_buf, fw_buf_len);
			unsigned int sz = fw_buf_len;
			free(fw_buf);
			fw_buf = NULL;
			fw_buf_len = 0;

			if (r == 0)
				snprintf(g_upgrade_page, sizeof(g_upgrade_page),
					 "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n"
					 "Connection: close\r\n\r\n"
					 "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
					 "<title>升级成功</title><style>"
					 "body{font-family:Arial;background:#1a1a2e;color:#e0e0e0;padding:30px;text-align:center}"
					 ".card{max-width:400px;margin:0 auto;background:#16213e;border:1px solid #0f3460;"
					 "border-radius:8px;padding:24px}"
					 "h1{color:#00ff88;font-size:18px}"
					 "p{color:#ccc;font-size:13px;margin:8px 0}"
					 ".btn{display:inline-block;background:#e94560;color:#fff;padding:8px 20px;"
					 "border-radius:4px;text-decoration:none;margin-top:12px;font-size:13px}"
					 "</style></head><body><div class=\"card\">"
					 "<h1>固件升级成功!</h1>"
					 "<p>刷写大小: %u 字节</p>"
					 "<p><a class=\"btn\" href=\"/\">返回首页</a></p>"
					 "</div></body></html>", sz);
			else
				snprintf(g_upgrade_page, sizeof(g_upgrade_page),
					 "HTTP/1.1 500 Internal Error\r\nContent-Type: text/html\r\n"
					 "Connection: close\r\n\r\n"
					 "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
					 "<title>升级失败</title><style>"
					 "body{font-family:Arial;background:#1a1a2e;color:#e0e0e0;padding:30px;text-align:center}"
					 ".card{max-width:400px;margin:0 auto;background:#16213e;border:1px solid #0f3460;"
					 "border-radius:8px;padding:24px}"
					 "h1{color:#ff6b6b;font-size:18px}"
					 "p{color:#ccc;font-size:13px}"
					 ".btn{display:inline-block;background:#e94560;color:#fff;padding:8px 20px;"
					 "border-radius:4px;text-decoration:none;margin-top:12px;font-size:13px}"
					 "</style></head><body><div class=\"card\">"
					 "<h1>固件升级失败!</h1>"
					 "<p>Flash 写入错误 (ret=%d)</p>"
					 "<p><a class=\"btn\" href=\"/\">返回首页</a></p>"
					 "</div></body></html>", r);

			http_send(pcb, g_upgrade_page, strlen(g_upgrade_page));
			tcp_output(pcb);
			http_close(pcb);
			free(conn);
		} else {
			tcp_recved(pcb, total);
		}
		return ERR_OK;
	}

	len = 0;
	for (struct pbuf *q = p; q; q = q->next)
		len += q->len;

	if (conn->req_len + len > 8192) {
		pbuf_free(p);
		http_close(pcb);
		free(conn->req_buf);
		free(conn);
		return ERR_OK;
	}

	conn->req_buf = realloc(conn->req_buf, conn->req_len + len + 1);
	memcpy(conn->req_buf + conn->req_len, p->payload, len);
	conn->req_len += len;
	conn->req_buf[conn->req_len] = '\0';
	pbuf_free(p);

	req = conn->req_buf;

	if (!strstr(req, "\r\n\r\n") && !strstr(req, "\n\n"))
		return ERR_OK;

	/* 解析请求行 */
	const char *method = req;
	const char *uri = strchr(req, ' ');
	if (!uri) { http_send(pcb, HTTP_BAD, strlen(HTTP_BAD)); goto cleanup; }
	uri++;
	const char *uri_end = strchr(uri, ' ');
	if (!uri_end) { http_send(pcb, HTTP_BAD, strlen(HTTP_BAD)); goto cleanup; }

	int uri_len = uri_end - uri;
	char parsed_uri[256] = {0};
	if (uri_len >= (int)sizeof(parsed_uri)) uri_len = sizeof(parsed_uri) - 1;
	strncpy(parsed_uri, uri, uri_len);

	if (!strncmp(method, "GET", 3)) {
		if (!strcmp(parsed_uri, "/") || !strcmp(parsed_uri, "/index.html")) {
			char buf[4096];
			const char *ip = ip4addr_ntoa(netif_ip4_addr(httpd_netif));
			unsigned long mem = gd->ram_size >> 20;
			snprintf(buf, sizeof(buf), g_index_html, PLAIN_VERSION, mem, ip);
			http_send(pcb, buf, strlen(buf));
		} else if (!strcmp(parsed_uri, "/reboot")) {
			const char *msg = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n"
				"Connection: close\r\n\r\n"
				"<html><body><h2>重启中...</h2></body></html>";
			http_send(pcb, msg, strlen(msg));
			tcp_output(pcb);
			http_close(pcb);
			free(conn->req_buf);
			free(conn);
			printf("httpd: 收到重启命令, 将在 3 秒后重置\n");
			for (int i = 0; i < 300; i++) {
				net_lwip_rx(eth_get_dev(), httpd_netif);
				mdelay(10);
			}
			do_reset(NULL, 0, 0, NULL);
			return ERR_OK;
		} else {
			http_send(pcb, HTTP_404, strlen(HTTP_404));
		}
		tcp_output(pcb);
		http_close(pcb);
	} else if (!strncmp(method, "POST", 4)) {
		const char *cl = strstr(req, "Content-Length:");
		if (!cl)
			cl = strstr(req, "content-length:");
		if (!cl) {
			http_send(pcb, HTTP_BAD, strlen(HTTP_BAD));
			goto cleanup;
		}
		fw_content_len = atoi(cl + 15);

	char *body = strstr(req, "\r\n\r\n");
	if (body) body += 4;
	else { body = strstr(req, "\n\n"); if (body) body += 2; }

	fw_buf = malloc(FW_BUF_MAX);
	fw_buf_len = 0;
	if (fw_buf && body) {
		int blen = conn->req_len - (body - req);
		if (blen > 0 && blen < (int)FW_BUF_MAX) {
			memcpy(fw_buf, body, blen);
			fw_buf_len = blen;
		}
	}

	/* 如果是非 multipart 的简单 POST，直接写入 flash */
	if (!strstr(req, "multipart/form-data")) {
		printf("httpd: 直接固件上传, %u 字节\n", fw_buf_len);
		int r = write_to_flash(fw_buf, fw_buf_len);
		unsigned int sz = fw_buf_len;
		free(fw_buf);
		fw_buf = NULL;
		fw_buf_len = 0;

		char page[1024];
		if (r == 0)
			snprintf(page, sizeof(page),
				 "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n"
				 "Connection: close\r\n\r\n"
				 "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
				 "<title>升级成功</title><style>"
				 "body{font-family:Arial;background:#1a1a2e;color:#e0e0e0;padding:30px;text-align:center}"
				 ".card{max-width:400px;margin:0 auto;background:#16213e;border:1px solid #0f3460;"
				 "border-radius:8px;padding:24px}"
				 "h1{color:#00ff88;font-size:18px}"
				 ".btn{display:inline-block;background:#e94560;color:#fff;padding:8px 20px;"
				 "border-radius:4px;text-decoration:none;margin-top:12px;font-size:13px}"
				 "</style></head><body><div class=\"card\">"
				 "<h1>升级成功</h1><p>刷写: %u 字节</p>"
				 "<p><a class=\"btn\" href=\"/\">返回首页</a></p>"
				 "</div></body></html>", sz);
		else
			snprintf(page, sizeof(page),
				 "HTTP/1.1 500 Internal Error\r\nContent-Type: text/html\r\n"
				 "Connection: close\r\n\r\n"
				 "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
				 "<title>升级失败</title><style>"
				 "body{font-family:Arial;background:#1a1a2e;color:#e0e0e0;padding:30px;text-align:center}"
				 ".card{max-width:400px;margin:0 auto;background:#16213e;border:1px solid #0f3460;"
				 "border-radius:8px;padding:24px}"
				 "h1{color:#ff6b6b;font-size:18px}"
				 ".btn{display:inline-block;background:#e94560;color:#fff;padding:8px 20px;"
				 "border-radius:4px;text-decoration:none;margin-top:12px;font-size:13px}"
				 "</style></head><body><div class=\"card\">"
				 "<h1>升级失败</h1><p>错误码: %d</p>"
				 "<p><a class=\"btn\" href=\"/\">返回首页</a></p>"
				 "</div></body></html>", r);

		http_send(pcb, page, strlen(page));
		tcp_output(pcb);
		http_close(pcb);
		free(conn->req_buf);
		free(conn);
		return ERR_OK;
	}
	} else {
		http_send(pcb, HTTP_BAD, strlen(HTTP_BAD));
		tcp_output(pcb);
		http_close(pcb);
	}

cleanup:
	free(conn->req_buf);
	free(conn);
	return ERR_OK;
}

static err_t http_accept_cb(void *arg, struct tcp_pcb *new_pcb, err_t err)
{
	struct http_conn *conn = calloc(1, sizeof(*conn));
	if (!conn) {
		tcp_close(new_pcb);
		return ERR_MEM;
	}
	conn->state = HTTP_RECV_REQ;
	tcp_arg(new_pcb, conn);
	tcp_recv(new_pcb, http_recv_cb);
	tcp_err(new_pcb, NULL);
	return ERR_OK;
}

static void httpd_start(void)
{
	httpd_pcb = tcp_new();
	if (!httpd_pcb) {
		printf("httpd: 创建 TCP PCB 失败\n");
		return;
	}
	err_t e = tcp_bind(httpd_pcb, IP_ADDR_ANY, HTTP_PORT);
	if (e != ERR_OK) {
		printf("httpd: 绑定端口 %d 失败: %d\n", HTTP_PORT, e);
		tcp_close(httpd_pcb);
		httpd_pcb = NULL;
		return;
	}
	httpd_pcb = tcp_listen(httpd_pcb);
	tcp_accept(httpd_pcb, http_accept_cb);
}

/* ========== DHCP ========== */

static void dhcp_fine_tmr_cb(void *ctx)
{
	dhcp_fine_tmr();
	sys_timeout(10, dhcp_fine_tmr_cb, NULL);
}

static int start_dhcp(struct udevice *udev)
{
	unsigned long start;

	httpd_netif = net_lwip_new_netif_noip(udev);
	if (!httpd_netif)
		return -ENODEV;

	start = get_timer(0);
	if (dhcp_start(httpd_netif))
		return -EIO;

	dhcp_fine_tmr_cb(NULL);

	do {
		net_lwip_rx(udev, httpd_netif);
		if (dhcp_supplied_address(httpd_netif))
			break;
		if (ctrlc()) {
			printf("中断\n");
			break;
		}
		mdelay(1);
	} while (get_timer(start) < DHCP_TIMEOUT_MS);

	if (!dhcp_supplied_address(httpd_netif))
		return -ETIMEDOUT;

	printf("httpd: DHCP 成功, IP: %s\n",
	       ip4addr_ntoa(netif_ip4_addr(httpd_netif)));
	return 0;
}

/* ========== 主循环 ========== */

static void httpd_main_loop(struct udevice *udev)
{
	unsigned long last = 0;

	printf("httpd: Web 服务器已启动, 端口 %d\n", HTTP_PORT);
	printf("httpd: 浏览器访问 http://%s/\n",
	       ip4addr_ntoa(netif_ip4_addr(httpd_netif)));
	printf("httpd: 按 Ctrl+C 停止\n");

	do {
		net_lwip_rx(udev, httpd_netif);
		if (get_timer(last) > 5000) {
			printf("httpd: 运行中... http://%s/\n",
			       ip4addr_ntoa(netif_ip4_addr(httpd_netif)));
			last = get_timer(0);
		}
		mdelay(HTTP_POLL_MS);
	} while (!ctrlc());

	sys_untimeout(dhcp_fine_tmr_cb, NULL);
	printf("httpd: 已停止\n");
}

static int do_httpd(struct cmd_tbl *cmdtp, int flag, int argc,
		    char *const argv[])
{
	struct udevice *udev;
	int ret;

	udev = eth_get_dev();
	if (!udev) {
		printf("httpd: 未找到网络设备\n");
		return CMD_RET_FAILURE;
	}

	ret = net_lwip_eth_start();
	if (ret < 0) {
		printf("httpd: 网络初始化失败\n");
		return CMD_RET_FAILURE;
	}

	ret = start_dhcp(udev);
	if (ret < 0) {
		printf("httpd: DHCP 失败, 尝试静态 IP\n");
		httpd_netif = net_lwip_new_netif(udev);
		if (!httpd_netif) {
			printf("httpd: 网络配置失败\n");
			eth_halt();
			return CMD_RET_FAILURE;
		}
	}

	httpd_start();
	if (!httpd_pcb) {
		net_lwip_remove_netif(httpd_netif);
		eth_halt();
		return CMD_RET_FAILURE;
	}

	httpd_main_loop(udev);

	if (httpd_pcb) {
		tcp_close(httpd_pcb);
		httpd_pcb = NULL;
	}
	net_lwip_remove_netif(httpd_netif);
	httpd_netif = NULL;
	eth_halt();

	return CMD_RET_SUCCESS;
}

U_BOOT_CMD(httpd, 1, 0, do_httpd,
	   "启动 Web 恢复/升级 HTTP 服务器",
	   "\n启动 HTTP 服务器, 提供 Web 固件升级界面\n"
	   "类似路由器\"不死 U-Boot\"功能\n");
